### ISSUE TITLE
artifacts.snapshot produced by //library/maven:update contains duplicates

### ISSUE THREAD

**Issue by haikalpribadi** [vaticle/dependencies#152]
See the `artifacts.snapshot` file from `@graknlabs_verification` linked below.

https://github.com/graknlabs/verification/blob/82012a1904d838dd675b680985a25460353d8665/dependencies/maven/artifacts.snapshot

We can see that each dependency artifact is written twice: once with the version, and once without. Is this expected? This feels like a bug. Can we fix it so that it just outputs one artifact once just with the version?

**Comment by lukas-slezevicius** [comment]
We've noticed that repos such as `typedb-client-java` are still using the bash script `update.sh` and it looks like they should instead be using `@vaticle_dependencies//library/maven:update`.

Maybe this is because of this issue where the kotlin script isn't working as intended.

**Comment by lolski** [comment]
> We can see that each dependency artifact is written twice: once with the version, and once without. Is this expected?

@haikalpribadi yes, it is expected and not a bug. It is the raw output produced by the `bazel query`, which is what the `update` script use under the hood.

> We've noticed that repos such as typedb-client-java are still using the bash script update.sh and it looks like they should instead be using @vaticle_dependencies//library/maven:update.

@lukas-slezevicius The [update.sh script](https://github.com/vaticle/typedb-client-java/blob/master/dependencies/maven/update.sh) actually calls `@vaticle_dependencies//library/maven:update` under the hood.

**Comment by alexjpwalker** [comment]
@lolski cc @haikalpribadi This is fairly easy to implement in the way described actually (although it does make the `//library/maven:update` code slightly weirder)

Each non-versioned `@maven` target is a `jvm_import`. Each versioned `@maven` target is an `alias` that aliases the non-versioned target.

Therefore we can halve the size of `artifacts.snapshot` by changing the invocation
```
bazel query @maven//...
```
to
```
bazel query 'kind(alias, @maven//...)'
```

**Comment by haikalpribadi** [comment]
That makes total sense, @alexjpwalker , let's go with your suggestion!
