### ISSUE TITLE
Extend `//tool/util:create-systemd-service`

### ISSUE THREAD

**Issue by vmax** [vaticle/dependencies#259]
We need to support remote profiling (JMX); correct set of options for this to work is:

```
SERVER_JAVAOPTS="-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=1089 -Dcom.sun.management.jmxremote.rmi.port=1089 -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Djava.rmi.server.hostname=<PUBLIC IP>"
```

**Comment by haikalpribadi** [comment]
when you're extending this, make sure to make the port number configurable through an argument. 
1) this makes the user have the control on which port to set and open.
2) this makes it clear and explicit to the user which port is expected to be used from VisualVM

**Comment by alexjpwalker** [comment]
@lolski Do you remember what we needed this for? Is it still useful to us as we move away from Java?
