### ISSUE TITLE
Implement the bump workflow across repositories

### ISSUE THREAD

**Issue by lolski** [vaticle/dependencies#265]
Adds a bump job that:

1. Increment the minor version in the VERSION file. We might have built a tool to do that that we can leverage out of the box. See the [PR](https://github.com/graknlabs/dependencies/pull/48) and the related [issue](https://github.com/graknlabs/dependencies/issues/47).
2. create new milestone according to that version

**Comment by alexjpwalker** [comment]
We're successfully using it in `web-main`:
```
bazel run @vaticle_dependencies//tool/release/version:bump
```
