### ISSUE TITLE
Cross-compilation of Rust code

### ISSUE THREAD

**Issue by vmax** [vaticle/dependencies#313]
Add support for "cross-compilation" of Rust code.

Cross-compilation refers to the ability to produce a binary targeted for a particular OS, with the compilation being done from a different OS. Adding such support would mean that we can, for example, produce a TypeDB Linux distribution from a Mac machine.

**Comment by lolski** [comment]
From an investigation done by Max, adding cross-compilation was not easy and we decided to not pursue cross-compilation. Therefore, in order to produce a binary for a specific OS, the compilation has to be done from that same OS.
