### ISSUE TITLE
Refactor //tool/release:create-notes to compile commit messages

### ISSUE THREAD

**Issue by haikalpribadi** [vaticle/dependencies#316]
Right now, `//tool/release:create-notes` would compile the messages from all issues and PRs from a given milestone, that has the same name as the release tag. This now needs to change, given the new mechanism in which we use milestones. To create draft release notes, we now need to simply compile all commit messages from all commits that are included in a given release, that are newly added since the last release.

**Comment by lolski** [comment]
The implementation has been done in https://github.com/vaticle/dependencies/pull/322 and https://github.com/vaticle/dependencies/pull/323.
