### ISSUE TITLE
//ci:release-docs should only bump the commit of docs in web-dev if ahead/diverged

### ISSUE THREAD

**Issue by haikalpribadi** [vaticle/dependencies#49]
If the CI workflow of an older commit in `docs` is being re-run, we don't want the `//ci:release-docs` to override the submodule reference of `docs` in `web-dev` to be overridden if it is more up to date than the older commit. Thus, we should only bump the commit of `docs` in `web-dev` if it is ahead/diverged.

You can see a reference implementation of this in: https://github.com/graknlabs/grabl/blob/5961de4a418b8bf4b2f1defe316b44ed5f04cfe4/git_repo.py#L372:L384

**Comment by alexjpwalker** [comment]
It looks like `//ci:release-docs` has been superseded by a newer workflow where pushing `docs` to `vaticle:master` triggers an automatic commit onto `web-docs`, and therefore this issue is no longer valid.
